### ISSUE TITLE
  Could not find package wp-cli.yml at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

### ISSUE THREAD

**Issue by s3w47m88** [PhilippBaschke/acf-pro-installer#13]
Firstly, thank you for taking the time to solve this problem.

In my case though, your solution isn't working. I'm getting two errors:

1. When I run `composer require advanced-custom-fields/advanced-custom-fields-pro: *` I get this error: `Could not find package wp-cli.yml at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

2. Unless I specify a specific ACF Pro version in composer.json I get this error: `  [Composer\Repository\InvalidRepositoryException]
  A repository of type "package" contains an invalid package definition: Invalid package information:
  version : invalid value (*.*.*(.*)): Invalid version string "*.*.*(.*)"
  Invalid package definition:
  {"name":"advanced-custom-fields\/advanced-custom-fields-pro","version":"*.*.*(.*)","type":"wordpress-plugin","dist":{"type":"zip","url":"https:\/\/connect.advancedcustomfields.com\/index.php?p=pro&a=
  download"},"require":{"philippbaschke\/acf-pro-installer":"^1.0","composer\/installers":"^1.0"}}`

Do you have any thoughts? Thank you for your time!

**Comment by s3w47m88** [comment]
Thank you for the swift response Philipp!

Here's my composer file in /bedrock/composer.js:
https://gist.github.com/s3w47m88/eab3a08b2ca3db9f96f5b92778b3f80c

Also here is my command line i/o:
https://gist.github.com/s3w47m88/341a52b77bfe31cfbb83e438f39a474d

As a side note, there is a typo in your instructions where it says: "composer require advanced-custom-fields/advanced-custom-fields-pro:*" - I believe it should have a space between ": *".

**Comment by PhilippBaschke** [comment]
Thank you for the detailed information. 😌 I think I found the error. 🤞 

But first to your side note: According to this https://github.com/composer/composer/issues/5118#issuecomment-202102719 it is important that no space is between `:` and the version (in your case `*`). So that is probably the reason for the `InvalidArgumentException`.

Your first try without the space fails because you are using `zsh` which interprets `*` as a wildcard. You are not the first to run into this problem (see: https://github.com/PhilippBaschke/acf-pro-installer/issues/9#issuecomment-266203629) and I should probably really add it to the README. ☺️ 

Please let me know if that helps 😌

**Comment by s3w47m88** [comment]
That makes sense. Now, are you saying I have to uninstall ZSH to run this? Forgive me, I'm not quiet clear on the solution (I also read the link you referenced).

Thank you for your time!

**Comment by PhilippBaschke** [comment]
Fortunately you can keep using ZSH (it's awesome after all) by using the green line from the linked issue:
`composer require advanced-custom-fields/advanced-custom-fields-pro:\*`

Hope that helps 😌

**Comment by s3w47m88** [comment]
I was able to get it working locally using that. I'll try on my original remote production machine in coming days and update here accordingly. Thanks so far!

**Comment by PhilippBaschke** [comment]
Glad I could help! 😌
