### ISSUE TITLE
Find ACF key in .env.* file

### ISSUE THREAD

**Issue by ccambournac** [PhilippBaschke/acf-pro-installer#15]
Hi,

it appears that the installer is looking the ACF key in a .env file only. It cannot read environment-specific files, like, e.g., .env.local ou .env.production files. Do you confirm? Is there a workaround?

Thanks anyway for your installer :)

**Comment by PhilippBaschke** [comment]
Thank you for your report @ccambournac 😌 
As you can see in in [Line 245](https://github.com/PhilippBaschke/acf-pro-installer/blob/master/src/ACFProInstaller/Plugin.php#L245) the plugin explicitly checks for `.env`:

```php
if (file_exists(getcwd().DIRECTORY_SEPARATOR.'.env')) {
...
```

`PHP dotenv` advises against using `.env` files in production in its [Usage Notes](https://github.com/vlucas/phpdotenv#usage-notes) which probably makes different versions of the file unnecessary. 

As far as I understand the `.env` convention you should create a `.env` file for every environment. So you would have a `.env` file on your local machine (instead of `.env.local`) and a `.env` file on your production server (instead of `.env.production`).

Let me know if you have any further questions! ☺️

**Comment by ccambournac** [comment]
Thanks for the reply @PhilippBaschke! It is crystal clear. ;)
Will have a unique and (already) ignored .env file from now on...
