### ISSUE TITLE
Can't install latest version

### ISSUE THREAD

**Issue by dmpinder** [PhilippBaschke/acf-pro-installer#18]
Hey,

I'm trying to install the latest version of ACF Pro using the following in composer.json:

```
        {
            "type": "package",
            "package": {
                "name": "advanced-custom-fields/advanced-custom-fields-pro",
                "version": "*",
                "type": "wordpress-plugin",
                "dist": {
                    "type": "zip",
                    "url": "https://connect.advancedcustomfields.com/index.php?p=pro&a=download"
                },
                "require": {
                    "philippbaschke/acf-pro-installer": "^1.0",
                    "composer/installers": "^1.0"
                }
            }
        }
```

and then below

```
    "require": {
        ...
        "advanced-custom-fields/advanced-custom-fields-pro": "*",
        ...
    },
```

The issue I'm having is using `"version": "*"`. If I use a named version, then it works fine. If I try to use * then I get this error:

>   [Composer\Repository\InvalidRepositoryException]                                                                     
  A repository of type "package" contains an invalid package definition: Invalid package information:                  
  version : invalid value (*): Invalid version string "*"                                                              
  Invalid package definition:                                                                                          
  {"name":"advanced-custom-fields\/advanced-custom-fields-pro","version":"*","type":"wordpress-plugin","dist":{"type"  
  :"zip","url":"https:\/\/connect.advancedcustomfields.com\/index.php?p=pro&a=download"},"require":{"philippbaschke\/  
  acf-pro-installer":"^1.0","composer\/installers":"^1.0"}}

Can you suggest a fix?

Thanks!

**Comment by tyrann0us** [comment]
Probably related to #2?
@elliotcondon should normalize his versioning. 😉

**Comment by elliotcondon** [comment]
Hi @tyrann0us 

Thanks mate. All ACF PRO versions are 3 digits only (not 4).
The latest version is 5.5.14 - is the problem being that the 'patch' is up to 14?
- This is pretty normal versioning.

Yes, in the past (over two years ago) I have used 4 dot points to define a version - crazy times.

Let me know if I can help out from my end.

**Comment by tyrann0us** [comment]
@elliotcondon, sorry for having bothered you. I somehow missed that v5.6.0 is indeed `5.6.0`, not `5.6` as I originally assumed.

@dmpinder, `"version": "5.6.0",` should work. At least it does for me.

**Comment by dmpinder** [comment]
@tyrann0us Thanks for the reply (and @elliotcondon!)

Fixed version numbers work, but I'd love to use `"version": "*"` to keep installing the latest version. Is that possible?

**Comment by PhilippBaschke** [comment]
Thanks for answering @tyrann0us and @elliotcondon ! 👍 

@dmpinder Unfortunately that is not possible. You add this code to the `repositories` section of `composer.json`

```json
{
  "type": "package",
  "package": {
    "name": "advanced-custom-fields/advanced-custom-fields-pro",
    "version": "5.6.0",
    "type": "wordpress-plugin",
    "dist": {
      "type": "zip",
      "url": "https://connect.advancedcustomfields.com/index.php?p=pro&a=download"
    },
    "require": {
      "philippbaschke/acf-pro-installer": "^1.0",
      "composer/installers": "^1.0"
    }
  }
}
```
This tells `composer` the following things:
- Apart from the standard repository [packagist](https://packagist.org/) you can also use this custom repository to find packages that I might want to install
- You tell it which `package` your new repository contains: "Hey `composer`, whenever you want to install `advanced-custom-fields/advanced-custom-fields-pro` in this specific version (here: `5.6.0`) I know where to get that from"

All `composer` repositories can only contain specific packages (see: [acf-pro-installer](https://packagist.org/packages/philippbaschke/acf-pro-installer) that contains `v0.1.0`, `v0.2.0`, `v1.0.0`, `v1.0.1`, `v1.0.2` and `dev-master`).

You can then `require` the package with `*` and get the latest version (`v1.0.2`) but packagist will still only have packages with specific version numbers.

Since our `package` repository can only contain one package with a specific version, we are forced to update the version in the `package` repository whenever we want to update 😞 

I hope that helps to understand it a little ☺️

**Comment by dmpinder** [comment]
Thanks for the reply @PhilippBaschke, that's pretty much what I've got now, but thanks for clarifying the version numbers. 

I've got about 60 sites using ACF Pro, and I'm currently converting them all to use Composer to install everything (WP in a sub-folder too), do you have any recommendations on the best way to keep the most up-to-date version of ACF Pro? I can update the plugin on production when an update is available, but then I'm running `composer update` on repo changes, so this would reset ACF Pro back to the version in Composer.

**Comment by PhilippBaschke** [comment]
@dmpinder Sorry for the late answer. We could maybe try it with a `dev-latest` version (`acf-pro-installer` could not add the version string to the URL in that case). But that might not really solve your problem because the following limitations are true for `package` repositories:

> Note: This repository type has a few limitations and should be avoided whenever possible:
> 
>  - Composer will not update the package unless you change the version field.
>  - Composer will not update the commit references, so if you use master as reference you will have to delete the package to force an update, and will have to deal with an unstable lock file.

See: [Composer Documentation](https://getcomposer.org/doc/05-repositories.md#package-2)

**Comment by mickaelperrin** [comment]
I opened an issue [here](https://github.com/AdvancedCustomFields/acf/issues/2) related to the auto-upgrade feature
