### ISSUE TITLE
Support other packages 

### ISSUE THREAD

**Issue by tillkruss** [PhilippBaschke/acf-pro-installer#8]
Hey!

I've got a few more packages that could use this installer. Do you want to add support for that or should I fork and make my own that is more generic.

**Comment by PhilippBaschke** [comment]
Thank you for your question @tillkruss. I have been thinking about making a more general version of this. Which plugins do you have in mind?

But I would also make a fork if I would do a more general version, so feel free to do that yourself. Let me know if you would prefer if I would do it (and if you have some time because I am pretty busy at the moment) and if you have any questions 😊

**Comment by tillkruss** [comment]
Time is exactly my problem, too 😀 
I'll see if I can come up with something this weekend.

We are using ACF Pro and AccessAlly.

**Comment by tyrann0us** [comment]
Another plugin which currently can't be installed with composer: [wpSEO](https://wpseo.de/).

**Comment by PhilippBaschke** [comment]
Thanks for the input @tyrann0us 👍  I added it to the list of plugins that I will try when doing the general fork ☺️

**Comment by tyrann0us** [comment]
All plugins from the developer of [WP All Import Pro](http://www.wpallimport.com/).

**Comment by tyrann0us** [comment]
Hi @PhilippBaschke,
is there any progress on this? I'm slowly using more and more premium plugins which fill my repos ...

Another candidate you could add to your list is [WP Migrate DB Pro](https://deliciousbrains.com/wp-migrate-db-pro/) and all addons.
Thanks!

**Comment by PhilippBaschke** [comment]
Unfortunately no progress 😞 But thank you for the further suggestions. The more the better! 😌

**Comment by christianmagill** [comment]
I definitely would love to see support for Gravity Forms!
